// GENERATED by scripts/build-guide.mjs — do not edit.
// Source: docs/guide/**/*.md. Run `pnpm guide:build` after changing a page.

/*
 * Titles, summaries and heading text — no HTML.
 *
 * Safe to import from a client component, which is the point: the sidebar and
 * its search filter this in memory, so there is no index to fetch and no
 * search dependency, and the guide's whole client footprint stays small enough
 * that check:budget never notices it.
 */

/*
 * The ids, as unions.
 *
 * They live here rather than in the hand-written types file because they are
 * derived from the group table in scripts/build-guide.mjs — a hand-written
 * copy is a copy that disagrees the first time a group is added.
 */
export type GuideAudienceId = "merchant" | "integrator" | "engineering";
export type GuideGroupId = "start" | "setup" | "selling" | "builder" | "running" | "help" | "api" | "mcp" | "engineering";

export type GuideAudience = {
  id: GuideAudienceId;
  label: string;
  blurb: string;
  noindex: boolean;
};

export type GuideNavGroup = {
  id: GuideGroupId;
  audience: GuideAudienceId;
  title: string;
  blurb: string;
};

export type GuideNavPage = {
  slug: string;
  group: GuideGroupId;
  audience: GuideAudienceId;
  order: number;
  title: string;
  summary: string;
  /** Heading text, so search finds a page by something inside it. */
  headings: string[];
};

export const GUIDE_AUDIENCES: GuideAudience[] = [
  {
    "id": "merchant",
    "label": "Using BuilderHut",
    "blurb": "For the person running the shop.",
    "noindex": false
  },
  {
    "id": "integrator",
    "label": "API and MCP",
    "blurb": "For building against BuilderHut.",
    "noindex": false
  },
  {
    "id": "engineering",
    "label": "How it is built",
    "blurb": "For working on BuilderHut itself.",
    "noindex": true
  }
];

export const GUIDE_NAV_GROUPS: GuideNavGroup[] = [
  {
    "id": "start",
    "audience": "merchant",
    "title": "Start here",
    "blurb": "What BuilderHut is, getting an account, and finding your way around."
  },
  {
    "id": "setup",
    "audience": "merchant",
    "title": "Setting up your shop",
    "blurb": "The questions at the start, choosing a template, and your shop's address."
  },
  {
    "id": "selling",
    "audience": "merchant",
    "title": "What you sell",
    "blurb": "Products, pictures, prices, delivery, tax and discount codes."
  },
  {
    "id": "builder",
    "audience": "merchant",
    "title": "The builder",
    "blurb": "Sections, the settings panel, style, previewing and publishing."
  },
  {
    "id": "running",
    "audience": "merchant",
    "title": "Running the shop",
    "blurb": "Orders, refunds, customers, the numbers, your domain, your team and your plan."
  },
  {
    "id": "help",
    "audience": "merchant",
    "title": "Help",
    "blurb": "How do I, what to do when something looks wrong, and what the words mean."
  },
  {
    "id": "api",
    "audience": "integrator",
    "title": "REST API",
    "blurb": "Tokens, conventions, errors, rate limits, and every endpoint."
  },
  {
    "id": "mcp",
    "audience": "integrator",
    "title": "MCP",
    "blurb": "Connecting an assistant to a shop, and the tools it gets."
  },
  {
    "id": "engineering",
    "audience": "engineering",
    "title": "How it is built",
    "blurb": "Architecture, tenancy, the document model, the render pipeline and the gates."
  }
];

export const GUIDE_NAV: GuideNavPage[] = [
  {
    "slug": "welcome",
    "group": "start",
    "audience": "merchant",
    "order": 10,
    "title": "What BuilderHut is",
    "summary": "A shop of your own, built by clicking rather than coding, with a real basket and a real checkout.",
    "headings": [
      "What you end up with",
      "How long it takes",
      "What it costs to try",
      "Things worth knowing early"
    ]
  },
  {
    "slug": "what-you-need",
    "group": "start",
    "audience": "merchant",
    "order": 20,
    "title": "What to have ready",
    "summary": "The four things worth gathering before you start, and the one decision that is easier to make now than later.",
    "headings": [
      "Photographs",
      "What things cost",
      "A few sentences about what you make",
      "A name, and the address that comes with it",
      "The one decision worth making now"
    ]
  },
  {
    "slug": "signing-up",
    "group": "start",
    "audience": "merchant",
    "order": 30,
    "title": "Making an account",
    "summary": "An email address, a password, and a six-digit code — and what to do when the code does not arrive.",
    "headings": [
      "Why the code",
      "Choosing a password",
      "Signing in afterwards"
    ]
  },
  {
    "slug": "the-questions",
    "group": "setup",
    "audience": "merchant",
    "order": 40,
    "title": "The questions at the start",
    "summary": "Five questions that decide your starting point, your currency and whether you need a checkout at all.",
    "headings": [
      "What do you make",
      "What is it called",
      "How you sell today",
      "What you want the shop to do",
      "Where you are",
      "What happens when you finish"
    ]
  },
  {
    "slug": "choosing-a-template",
    "group": "setup",
    "audience": "merchant",
    "order": 50,
    "title": "Choosing a starting point",
    "summary": "Twelve of them, each a whole site rather than a colour scheme — and every part of one is yours to change.",
    "headings": [
      "They differ in structure, not just colour",
      "What you can change afterwards"
    ]
  },
  {
    "slug": "your-products",
    "group": "selling",
    "audience": "merchant",
    "order": 60,
    "title": "Adding what you sell",
    "summary": "A name, a description, a price and a photograph — and what each of them does on the shop.",
    "headings": [
      "The name",
      "The description",
      "The price",
      "A compare-at price makes a discount",
      "Draft, active, archived"
    ]
  },
  {
    "slug": "pictures",
    "group": "selling",
    "audience": "merchant",
    "order": 65,
    "title": "Pictures",
    "summary": "How photographs are shrunk before they are sent, how to order them, and what makes one work on a shop.",
    "headings": [
      "They are shrunk in your browser",
      "The first one matters most",
      "Describing a picture",
      "What is accepted",
      "The media library"
    ]
  },
  {
    "slug": "the-three-columns",
    "group": "builder",
    "audience": "merchant",
    "order": 70,
    "title": "The three columns",
    "summary": "Sections on the left, the page in the middle, the settings for whatever you clicked on the right — and why the middle is not a preview.",
    "headings": [
      "The middle is not a preview",
      "The left panel",
      "The right panel",
      "Undo"
    ]
  },
  {
    "slug": "publishing",
    "group": "builder",
    "audience": "merchant",
    "order": 80,
    "title": "Previewing and publishing",
    "summary": "What preview actually shows you, what publishing checks before it lets anything go public, and how to go back.",
    "headings": [
      "Preview",
      "Publishing",
      "Going back"
    ]
  },
  {
    "slug": "orders",
    "group": "running",
    "audience": "merchant",
    "order": 90,
    "title": "Orders and refunds",
    "summary": "Why an order only offers some of the next steps, and why a refund is partial unless you say otherwise.",
    "headings": [
      "An order is a state machine, not a status field",
      "Refunds are partial by default",
      "What the revenue figure counts",
      "When a payment fails"
    ]
  },
  {
    "slug": "how-do-i",
    "group": "help",
    "audience": "merchant",
    "order": 100,
    "title": "How do I…",
    "summary": "Short answers to the things people look up mid-task.",
    "headings": [
      "When something looks wrong"
    ]
  },
  {
    "slug": "overview",
    "group": "api",
    "audience": "integrator",
    "order": 200,
    "title": "The API, in outline",
    "summary": "What the REST API covers, what it deliberately does not, and how a request is authorised.",
    "headings": [
      "The shape of every response",
      "What a token can be allowed to do",
      "What the API does not do"
    ]
  },
  {
    "slug": "overview",
    "group": "mcp",
    "audience": "integrator",
    "order": 300,
    "title": "The MCP server",
    "summary": "What connecting an assistant to a shop means, what it can and cannot do, and how to decide before you do it.",
    "headings": [
      "What it will not do",
      "Scopes are enforced, not just filtered"
    ]
  },
  {
    "slug": "architecture",
    "group": "engineering",
    "audience": "engineering",
    "order": 400,
    "title": "Architecture at a glance",
    "summary": "The five surfaces, the one door to merchant data, and the single renderer behind the builder and the live shop.",
    "headings": [
      "The five surfaces",
      "The one door",
      "One renderer, three surfaces",
      "Where to look first"
    ]
  }
];
