// GENERATED by scripts/build-guide.mjs — do not edit.
// Source: docs/guide/**/*.md. Run `pnpm guide:build` after changing a page.

/*
 * Titles, summaries and heading text — no HTML.
 *
 * Safe to import from a client component, which is the point: the sidebar and
 * its search filter this in memory, so there is no index to fetch and no
 * search dependency, and the guide's whole client footprint stays small enough
 * that check:budget never notices it.
 */

/*
 * The ids, as unions.
 *
 * They live here rather than in the hand-written types file because they are
 * derived from the group table in scripts/build-guide.mjs — a hand-written
 * copy is a copy that disagrees the first time a group is added.
 */
export type GuideAudienceId = "merchant" | "integrator" | "engineering";
export type GuideGroupId = "start" | "setup" | "selling" | "builder" | "running" | "help" | "api" | "mcp" | "engineering";

export type GuideAudience = {
  id: GuideAudienceId;
  label: string;
  blurb: string;
  noindex: boolean;
};

export type GuideNavGroup = {
  id: GuideGroupId;
  audience: GuideAudienceId;
  title: string;
  blurb: string;
};

export type GuideNavPage = {
  slug: string;
  group: GuideGroupId;
  audience: GuideAudienceId;
  order: number;
  title: string;
  summary: string;
  /** Heading text, so search finds a page by something inside it. */
  headings: string[];
};

export const GUIDE_AUDIENCES: GuideAudience[] = [
  {
    "id": "merchant",
    "label": "Using BuilderHut",
    "blurb": "For the person running the shop.",
    "noindex": false
  },
  {
    "id": "integrator",
    "label": "API and MCP",
    "blurb": "For building against BuilderHut.",
    "noindex": false
  },
  {
    "id": "engineering",
    "label": "How it is built",
    "blurb": "For working on BuilderHut itself.",
    "noindex": true
  }
];

export const GUIDE_NAV_GROUPS: GuideNavGroup[] = [
  {
    "id": "start",
    "audience": "merchant",
    "title": "Start here",
    "blurb": "What BuilderHut is, getting an account, and finding your way around."
  },
  {
    "id": "setup",
    "audience": "merchant",
    "title": "Setting up your shop",
    "blurb": "The questions at the start, choosing a template, and your shop's address."
  },
  {
    "id": "selling",
    "audience": "merchant",
    "title": "What you sell",
    "blurb": "Products, pictures, prices, delivery, tax and discount codes."
  },
  {
    "id": "builder",
    "audience": "merchant",
    "title": "The builder",
    "blurb": "Sections, the settings panel, style, previewing and publishing."
  },
  {
    "id": "running",
    "audience": "merchant",
    "title": "Running the shop",
    "blurb": "Orders, refunds, customers, the numbers, your domain, your team and your plan."
  },
  {
    "id": "help",
    "audience": "merchant",
    "title": "Help",
    "blurb": "How do I, what to do when something looks wrong, and what the words mean."
  },
  {
    "id": "api",
    "audience": "integrator",
    "title": "REST API",
    "blurb": "Tokens, conventions, errors, rate limits, and every endpoint."
  },
  {
    "id": "mcp",
    "audience": "integrator",
    "title": "MCP",
    "blurb": "Connecting an assistant to a shop, and the tools it gets."
  },
  {
    "id": "engineering",
    "audience": "engineering",
    "title": "How it is built",
    "blurb": "Architecture, tenancy, the document model, the render pipeline and the gates."
  }
];

export const GUIDE_NAV: GuideNavPage[] = [
  {
    "slug": "welcome",
    "group": "start",
    "audience": "merchant",
    "order": 10,
    "title": "What BuilderHut is",
    "summary": "A shop of your own, built by clicking rather than coding, with a real basket and a real checkout.",
    "headings": [
      "What you end up with",
      "How long it takes",
      "What it costs to try",
      "Things worth knowing early"
    ]
  },
  {
    "slug": "what-you-need",
    "group": "start",
    "audience": "merchant",
    "order": 20,
    "title": "What to have ready",
    "summary": "The four things worth gathering before you start, and the one decision that is easier to make now than later.",
    "headings": [
      "Photographs",
      "What things cost",
      "A few sentences about what you make",
      "A name, and the address that comes with it",
      "The one decision worth making now"
    ]
  },
  {
    "slug": "signing-up",
    "group": "start",
    "audience": "merchant",
    "order": 30,
    "title": "Making an account",
    "summary": "An email address, a password, and a six-digit code — and what to do when the code does not arrive.",
    "headings": [
      "Why the code",
      "Choosing a password",
      "Signing in afterwards"
    ]
  },
  {
    "slug": "the-questions",
    "group": "setup",
    "audience": "merchant",
    "order": 40,
    "title": "The questions at the start",
    "summary": "Five questions that decide your starting point, your currency and whether you need a checkout at all.",
    "headings": [
      "What do you make",
      "What is it called",
      "How you sell today",
      "What you want the shop to do",
      "Where you are",
      "What happens when you finish"
    ]
  },
  {
    "slug": "choosing-a-template",
    "group": "setup",
    "audience": "merchant",
    "order": 50,
    "title": "Choosing a starting point",
    "summary": "Twelve of them, each a whole site rather than a colour scheme — and every part of one is yours to change.",
    "headings": [
      "They differ in structure, not just colour",
      "What you can change afterwards"
    ]
  },
  {
    "slug": "your-products",
    "group": "selling",
    "audience": "merchant",
    "order": 60,
    "title": "Adding what you sell",
    "summary": "A name, a description, a price and a photograph — and what each of them does on the shop.",
    "headings": [
      "The name",
      "The description",
      "The price",
      "A compare-at price makes a discount",
      "Draft, active, archived"
    ]
  },
  {
    "slug": "pictures",
    "group": "selling",
    "audience": "merchant",
    "order": 65,
    "title": "Pictures",
    "summary": "How photographs are shrunk before they are sent, how to order them, and what makes one work on a shop.",
    "headings": [
      "They are shrunk in your browser",
      "The first one matters most",
      "Describing a picture",
      "What is accepted",
      "The media library"
    ]
  },
  {
    "slug": "delivery",
    "group": "selling",
    "audience": "merchant",
    "order": 67,
    "title": "Delivery",
    "summary": "Zones and rates, why a shop cannot publish without one, and the three ways to charge.",
    "headings": [
      "Why this blocks publishing",
      "The three kinds of rate",
      "Several rates in one zone",
      "What the customer sees"
    ]
  },
  {
    "slug": "tax",
    "group": "selling",
    "audience": "merchant",
    "order": 68,
    "title": "Tax",
    "summary": "Tax rules, inclusive versus exclusive pricing, and the fields Indian shops need.",
    "headings": [
      "Inclusive or exclusive",
      "Rules",
      "GSTIN and HSN",
      "How tax is worked out"
    ]
  },
  {
    "slug": "discounts",
    "group": "selling",
    "audience": "merchant",
    "order": 69,
    "title": "Discount codes",
    "summary": "Codes people type at checkout, how they differ from a compare-at price, and the limits worth setting.",
    "headings": [
      "The three kinds",
      "Limits worth setting",
      "Writing a code",
      "What the customer sees"
    ]
  },
  {
    "slug": "the-three-columns",
    "group": "builder",
    "audience": "merchant",
    "order": 70,
    "title": "The three columns",
    "summary": "Sections on the left, the page in the middle, the settings for whatever you clicked on the right — and why the middle is not a preview.",
    "headings": [
      "The middle is not a preview",
      "The left panel",
      "The right panel",
      "Undo"
    ]
  },
  {
    "slug": "adding-sections",
    "group": "builder",
    "audience": "merchant",
    "order": 71,
    "title": "Adding and arranging sections",
    "summary": "What a section is, where a new one lands, and how to move, duplicate, hide or remove one.",
    "headings": [
      "Where a new one lands",
      "The twelve sections",
      "Moving one",
      "Duplicating",
      "Hiding rather than deleting"
    ]
  },
  {
    "slug": "the-settings-panel",
    "group": "builder",
    "audience": "merchant",
    "order": 72,
    "title": "The settings panel",
    "summary": "The right-hand column, which shows only the controls that apply to whatever you clicked.",
    "headings": [
      "The kinds of control",
      "Why the choices are named",
      "Per-section notes worth knowing"
    ]
  },
  {
    "slug": "style",
    "group": "builder",
    "audience": "merchant",
    "order": 73,
    "title": "Style — colour, type and shape",
    "summary": "The theme editor, and why colour is nine roles rather than a colour picker.",
    "headings": [
      "Colour, as nine roles",
      "Type",
      "Shape",
      "Your shop s colours are yours"
    ]
  },
  {
    "slug": "layers-and-pages",
    "group": "builder",
    "audience": "merchant",
    "order": 74,
    "title": "Layers and pages",
    "summary": "The whole page as a list, and the pages of the shop — including the ones you cannot delete.",
    "headings": [
      "Layers",
      "Pages",
      "Adding a page"
    ]
  },
  {
    "slug": "phone-and-tablet",
    "group": "builder",
    "audience": "merchant",
    "order": 75,
    "title": "Phone and tablet",
    "summary": "Why narrowing the canvas shows exactly what a phone shows, and the few things worth checking there.",
    "headings": [
      "They are widths, not emulations",
      "What is worth checking",
      "On a phone, the builder itself"
    ]
  },
  {
    "slug": "undo-and-versions",
    "group": "builder",
    "audience": "merchant",
    "order": 76,
    "title": "Undo, saving and version history",
    "summary": "What counts as one undo step, when your work is saved, and how to go back to last week.",
    "headings": [
      "Saving",
      "Undo",
      "Version history"
    ]
  },
  {
    "slug": "publishing",
    "group": "builder",
    "audience": "merchant",
    "order": 80,
    "title": "Previewing and publishing",
    "summary": "What preview actually shows you, what publishing checks before it lets anything go public, and how to go back.",
    "headings": [
      "Preview",
      "Publishing",
      "Going back"
    ]
  },
  {
    "slug": "the-dashboard",
    "group": "running",
    "audience": "merchant",
    "order": 85,
    "title": "The dashboard",
    "summary": "What the front page of your shop's admin shows, and why the checklist comes before the numbers.",
    "headings": [
      "The checklist comes first",
      "The numbers",
      "Every comparison says what it compares to",
      "On a phone"
    ]
  },
  {
    "slug": "orders",
    "group": "running",
    "audience": "merchant",
    "order": 90,
    "title": "Orders and refunds",
    "summary": "Why an order only offers some of the next steps, and why a refund is partial unless you say otherwise.",
    "headings": [
      "An order is a state machine, not a status field",
      "Refunds are partial by default",
      "What the revenue figure counts",
      "When a payment fails"
    ]
  },
  {
    "slug": "customers",
    "group": "running",
    "audience": "merchant",
    "order": 91,
    "title": "Customers",
    "summary": "Who has bought from you, what you can see, and what is deliberately not collected.",
    "headings": [
      "What is here",
      "What is not collected",
      "Customers are per shop",
      "Contacting people"
    ]
  },
  {
    "slug": "analytics",
    "group": "running",
    "audience": "merchant",
    "order": 92,
    "title": "The numbers",
    "summary": "What is counted, what each figure is compared against, and how much to read into it early on.",
    "headings": [
      "What is counted",
      "Today and history are stored differently",
      "How much to read into it",
      "What the numbers cannot tell you"
    ]
  },
  {
    "slug": "your-web-address",
    "group": "running",
    "audience": "merchant",
    "order": 93,
    "title": "Your web address",
    "summary": "The address your shop gets for free, and how to point a domain you own at it.",
    "headings": [
      "Using a domain you own",
      "Why the redirect matters",
      "Buying a domain"
    ]
  },
  {
    "slug": "how-do-i",
    "group": "help",
    "audience": "merchant",
    "order": 100,
    "title": "How do I…",
    "summary": "Short answers to the things people look up mid-task.",
    "headings": [
      "When something looks wrong"
    ]
  },
  {
    "slug": "overview",
    "group": "api",
    "audience": "integrator",
    "order": 200,
    "title": "The API, in outline",
    "summary": "What the REST API covers, what it deliberately does not, and how a request is authorised.",
    "headings": [
      "The shape of every response",
      "What a token can be allowed to do",
      "What the API does not do"
    ]
  },
  {
    "slug": "authentication",
    "group": "api",
    "audience": "integrator",
    "order": 210,
    "title": "Authentication",
    "summary": "Personal access tokens — what they stand for, how to scope them, and why the role is read live.",
    "headings": [
      "What a token is",
      "The role is read live",
      "Scopes",
      "Three checks, narrowest wins",
      "Losing one"
    ]
  },
  {
    "slug": "errors",
    "group": "api",
    "audience": "integrator",
    "order": 220,
    "title": "Errors",
    "summary": "The envelope every failure uses, what each code means, and why a resource in another shop is a 404.",
    "headings": [
      "The codes",
      "Unknown, expired and revoked are the same answer",
      "A resource in another shop is 404, not 403",
      "Errors never leak internals",
      "Retrying"
    ]
  },
  {
    "slug": "overview",
    "group": "mcp",
    "audience": "integrator",
    "order": 300,
    "title": "The MCP server",
    "summary": "What connecting an assistant to a shop means, what it can and cannot do, and how to decide before you do it.",
    "headings": [
      "What it will not do",
      "Scopes are enforced, not just filtered"
    ]
  },
  {
    "slug": "architecture",
    "group": "engineering",
    "audience": "engineering",
    "order": 400,
    "title": "Architecture at a glance",
    "summary": "The five surfaces, the one door to merchant data, and the single renderer behind the builder and the live shop.",
    "headings": [
      "The five surfaces",
      "The one door",
      "One renderer, three surfaces",
      "Where to look first"
    ]
  }
];
